import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  if (session) {
    return (
      <>
        Signed in as {session}
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Not signed in
      <button
        onClick={() =>
          signIn(null, {
            callbackUrl:
              "https://idpsesion.telecom.com.ar/openam/oauth2/realms/convergente/authorize?response_type=code",
          })
        }
      >
        Login auth
      </button>
    </div>
  );
}
